# semantic_analyzer.py
# Semantic Analyzer and Symbol Table for the MiniLang Compiler Front-End.
#
# Semantic rules:
# 1. A variable must be declared before it is assigned.
# 2. A variable must be declared before it is used.
# 3. A variable cannot be declared more than once.
# 4. All MiniLang variables have the type "int".


class SemanticAnalyzer:
    """Performs semantic analysis on a valid MiniLang token stream."""

    def __init__(self, tokens):
        """
        Initialize the semantic analyzer.

        Args:
            tokens: Tokens generated by the lexical analyzer.
        """

        self.tokens = tokens
        self.position = 0
        self.symbol_table = {}
        self.errors = []

    # ------------------------------------------------------------------
    # Token-handling methods
    # ------------------------------------------------------------------

    def current_token(self):
        """
        Return the current token.

        If every token has been processed, return an EOF token with a
        meaningful source-code position.
        """

        if self.position < len(self.tokens):
            return self.tokens[self.position]

        if self.tokens:
            _, token_value, line, column = self.tokens[-1]
            eof_column = column + len(str(token_value))

            return ("EOF", "EOF", line, eof_column)

        return ("EOF", "EOF", 1, 1)

    def advance(self):
        """Move to the next token."""

        if self.position < len(self.tokens):
            self.position += 1

    def add_error(self, line, column, message):
        """
        Add a semantic error to the error list.

        Args:
            line: Source-code line number.
            column: Source-code column number.
            message: Explanation of the semantic error.
        """

        self.errors.append(
            f"Semantic Error at line {line}, column {column}: "
            f"{message}"
        )

    def is_declared(self, variable_name):
        """Return True when a variable exists in the symbol table."""

        return variable_name in self.symbol_table

    # ------------------------------------------------------------------
    # Main analysis method
    # ------------------------------------------------------------------

    def analyze(self):
        """
        Analyze the complete MiniLang token stream.

        Returns:
            tuple:
                symbol_table: Declared variables and their details.
                errors: Semantic errors found during analysis.
        """

        while self.current_token()[0] != "EOF":
            starting_position = self.position

            token_type, token_value, _, _ = self.current_token()

            if token_type == "KEYWORD" and token_value == "int":
                self.analyze_declaration()

            elif token_type == "IDENTIFIER":
                self.analyze_assignment()

            elif token_type == "KEYWORD" and token_value == "print":
                self.analyze_print_statement()

            elif token_type == "KEYWORD" and token_value == "if":
                self.analyze_if_statement()

            else:
                # Includes braces and any token that does not begin a
                # semantic construct.
                self.advance()

            # Safety check: always ensure that analysis makes progress.
            if (
                self.position == starting_position
                and self.current_token()[0] != "EOF"
            ):
                self.advance()

        return self.symbol_table, self.errors

    # ------------------------------------------------------------------
    # Declaration analysis
    # ------------------------------------------------------------------

    def analyze_declaration(self):
        """
        Analyze a variable declaration.

        Expected syntax:
            int identifier = number ;
        """

        self.advance()  # Skip the 'int' keyword.

        token_type, token_value, line, column = self.current_token()

        if token_type == "IDENTIFIER":
            variable_name = token_value

            if self.is_declared(variable_name):
                previous_declaration = self.symbol_table[variable_name]
                previous_line = previous_declaration["declared_line"]

                self.add_error(
                    line,
                    column,
                    f"Variable '{variable_name}' is already declared "
                    f"at line {previous_line}."
                )

            else:
                self.symbol_table[variable_name] = {
                    "type": "int",
                    "declared_line": line,
                    "declared_column": column,
                    "initialized": True,
                }

        # Move to the end of the declaration.
        self.skip_until({"SEMICOLON", "EOF"})

        if self.current_token()[0] == "SEMICOLON":
            self.advance()

    # ------------------------------------------------------------------
    # Assignment analysis
    # ------------------------------------------------------------------

    def analyze_assignment(self):
        """
        Analyze an assignment statement.

        Expected syntax:
            identifier = Expression ;
        """

        token_type, variable_name, line, column = self.current_token()

        # Check the variable on the left-hand side of the assignment.
        if token_type == "IDENTIFIER":
            if not self.is_declared(variable_name):
                self.add_error(
                    line,
                    column,
                    f"Cannot assign to variable '{variable_name}' "
                    "because it has not been declared."
                )

        self.advance()  # Skip the left-hand-side identifier.

        # Analyze every identifier used in the expression.
        while self.current_token()[0] not in {"SEMICOLON", "EOF"}:
            token_type, token_value, line, column = self.current_token()

            if token_type == "IDENTIFIER":
                if not self.is_declared(token_value):
                    self.add_error(
                        line,
                        column,
                        f"Variable '{token_value}' is used in an "
                        "expression before declaration."
                    )

            self.advance()

        if self.current_token()[0] == "SEMICOLON":
            self.advance()

    # ------------------------------------------------------------------
    # Print-statement analysis
    # ------------------------------------------------------------------

    def analyze_print_statement(self):
        """
        Analyze a print statement.

        Expected syntax:
            print ( identifier ) ;
        """

        self.advance()  # Skip the 'print' keyword.

        while self.current_token()[0] not in {"SEMICOLON", "EOF"}:
            token_type, token_value, line, column = self.current_token()

            if token_type == "IDENTIFIER":
                if not self.is_declared(token_value):
                    self.add_error(
                        line,
                        column,
                        f"Variable '{token_value}' cannot be printed "
                        "because it has not been declared."
                    )

            self.advance()

        if self.current_token()[0] == "SEMICOLON":
            self.advance()

    # ------------------------------------------------------------------
    # If-statement analysis
    # ------------------------------------------------------------------

    def analyze_if_statement(self):
        """
        Analyze the condition of an if statement.

        Expected syntax:
            if identifier RelOp number { StatementList }
        """

        self.advance()  # Skip the 'if' keyword.

        # Analyze the condition until the opening brace is reached.
        while self.current_token()[0] not in {"LBRACE", "EOF"}:
            token_type, token_value, line, column = self.current_token()

            if token_type == "IDENTIFIER":
                if not self.is_declared(token_value):
                    self.add_error(
                        line,
                        column,
                        f"Variable '{token_value}' is used in a "
                        "condition before declaration."
                    )

            self.advance()

        # Consume the opening brace. Statements inside the block will then
        # be processed by the main analyze() loop.
        if self.current_token()[0] == "LBRACE":
            self.advance()

    # ------------------------------------------------------------------
    # Utility methods
    # ------------------------------------------------------------------

    def skip_until(self, safe_token_types):
        """
        Advance until one of the supplied token types is reached.

        Args:
            safe_token_types: Set of token types where scanning should stop.
        """

        while self.current_token()[0] not in safe_token_types:
            self.advance()


def analyze_semantics(tokens):
    """
    Perform semantic analysis on a MiniLang token stream.

    Args:
        tokens: Tokens previously validated by the parser.

    Returns:
        tuple:
            symbol_table: Information about declared variables.
            errors: Semantic errors found.
            is_semantically_valid: True when no semantic errors exist.
    """

    analyzer = SemanticAnalyzer(tokens)
    symbol_table, errors = analyzer.analyze()

    is_semantically_valid = len(errors) == 0

    return symbol_table, errors, is_semantically_valid


def main():
    """Run a basic semantic-analysis test."""

    from parser import parse_code

    sample_code = """
int x = 10;
x = x + 5;
print(x);

if x > 10 {
    x = x + 1;
}
"""

    tokens, syntax_errors, syntax_valid = parse_code(sample_code)

    if not syntax_valid:
        print("Syntax errors found. Semantic analysis skipped.")

        for error in syntax_errors:
            print(error)

        return

    symbol_table, semantic_errors, semantic_valid = analyze_semantics(tokens)

    print("SYMBOL TABLE")
    print("=" * 60)

    if symbol_table:
        for name, details in symbol_table.items():
            print(
                f"{name} -> "
                f"Type: {details['type']}, "
                f"Declared at line {details['declared_line']}, "
                f"column {details['declared_column']}, "
                f"Initialized: {details['initialized']}"
            )
    else:
        print("No variables declared.")

    print("\nSEMANTIC ANALYSIS")
    print("=" * 60)

    if semantic_valid:
        print("Semantic Analysis Passed.")
        print("No semantic errors found.")
    else:
        print("Semantic Analysis Failed.")

        for error in semantic_errors:
            print(error)


if __name__ == "__main__":
    main()